final applicationText = {
  'eng': {
    'appTitle': 'साड्डाVaahan',
    'searchHint': 'Search for bus number or route',
    'recentSearches': 'Recent Searches',
    'noRecentSearches': 'No recent searches',
    'floatIconText': 'Tap to speak',
    'appBarTitle': 'साड्डाVaahan',
    'drawerHeaderTitle': 'साड्डाVaahan',
    'recentSearchesTitle': 'Recent Searches',
    'noBusAvailable': 'No Bus Available on your selected route',
    'arrivingIn': "Arriving in ",
    'estimatedTime': "Estimated Duration ",
    'sortBy': "Sort By",
    'arrivalTimeEarliest': "Arrival Time (Earliest First)",
    'arrivalTimeLatest': "Arrival Time (Latest First)",
    'pickupDistanceNearest': "Pickup Distance (Nearest First)",
    'pickupDistanceFarthest': "Pickup Distance (Farthest First)",
    'dropDistanceNearest': "Drop Distance (Nearest First)",
    'dropDistanceFarthest': "Drop Distance (Farthest First)",
    'leavingHint': "Leaving from",
    'goingHint': "Going To",
    'departure': "Departure",
    'searchButton': "Find buses",
    'signInButtonText': "Login to see search history",
    'listening': "Listening...",
    'listeningHint': "Say your pickup and destination",
    'tapToStop': "Tap to stop early",
    'processing': "Processing...",
    'understanding': "Understanding your request...",
    'error': "An error occurred. Please try again.",
    'noSpeech': "No speech detected. Please try again.",
    'permissionDenied':
        "Microphone permission denied. Please enable it in settings.",
    'recordingHint': "Recording... Tap to stop",
    'retry': "Retry",
    'confirm': "Confirm",
    'cancel': "Cancel",
    'microphonePermission': "Microphone Permission",
    'recordAudio': "Record Audio",
    'recording': "Recording...",
    'processingRequest': "Processing your request...",
    'goToHomeText': "Go to Home",
    'recordingSuccess': "Recording Successful",
    'recordingFailed': "Recording Failed",
    'recordingComplete': "Recording Completed",
    'search': "Search",
    'leaveingHint': "Leaving from",
    'signOut': "Sign Out",
    'home': "Home",
    'language': "Language",
    'helpAndSupport': "Help & Support",
    'feedback': "Feedback",
    'about': "About",
    'welcome': "Welcome",
    'goToHomeButtonText': "Go to Home",

  },
  'hin': {
    'appTitle': 'साड्डावाहन',
    'searchHint': 'बस नंबर या मार्ग खोजें',
    'recentSearches': 'हाल की खोजें',
    'noRecentSearches': 'कोई हाल की खोज नहीं',
    'floatIconText': 'बोलने के लिए टैप करें',
    'appBarTitle': 'साड्डावाहन',
    'drawerHeaderTitle': 'सादीबस',
    'recentSearchesTitle': 'हाल की खोजें',
    'noBusAvailable': 'आपके चयनित मार्ग पर कोई बस उपलब्ध नहीं है',
    'arrivingIn': "आने में ",
    'estimatedTime': "अनुमानित अवधि ",
    'sortBy': "क्रमबद्ध करें",
    'arrivalTimeEarliest': "आगमन समय (सबसे पहले)",
    'arrivalTimeLatest': "आगमन समय (सबसे बाद में)",
    'pickupDistanceNearest': "पिकअप दूरी (सबसे नजदीक)",
    'pickupDistanceFarthest': "पिकअप दूरी (सबसे दूर)",
    'dropDistanceNearest': "ड्रॉप दूरी (सबसे नजदीक)",
    'dropDistanceFarthest': "ड्रॉप दूरी (सबसे दूर)",
    'leavingHint': "कहां से जा रहे हैं",
    'goingHint': "कहां जा रहे हैं",
    'departure': "प्रस्थान",
    'searchButton': "बसें खोजें",
    'signInButtonText': "खोज इतिहास देखने के लिए लॉगिन करें",
    'listening': "सुन रहा हूँ...",
    'listeningHint': "अपना पिकअप और गंतव्य बताएं",
    'tapToStop': "जल्दी रोकने के लिए टैप करें",
    'processing': "प्रसंस्करण...",
    'understanding': "आपके अनुरोध को समझना...",
    'error': "एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
    'noSpeech': "कोई भाषण नहीं सुना गया। कृपया पुनः प्रयास करें।",
    'permissionDenied':
        "माइक्रोफोन अनुमति अस्वीकृत। कृपया इसे सेटिंग्स में सक्षम करें।",
    'recordingHint': "रिकॉर्डिंग... रोकने के लिए टैप करें",
    'retry': "पुनः प्रयास करें",
    'confirm': "पुष्टि करें",
    'cancel': "रद्द करें",
    'microphonePermission': "माइक्रोफोन अनुमति",
    'recordAudio': "ऑडियो रिकॉर्ड करें",
    'recording': "रिकॉर्डिंग...",
    'processingRequest': "आपके अनुरोध को संसाधित कर रहा हूँ...",
    'goToHomeText': "होम पर जाएं",
    'recordingSuccess': "रिकॉर्डिंग सफल",
    'recordingFailed': "रिकॉर्डिंग विफल",
    'recordingComplete': "रिकॉर्डिंग पूरी हुई",
    'search': "खोज",
    'leaveingHint': "कहां से जा रहे हैं",
    'signOut': "साइन आउट",
    'home': "होम",
    'language': "भाषा",
    'helpAndSupport': "मदद और समर्थन",
    'feedback': "प्रतिक्रिया",
    'about': "के बारे में",
    'welcome': "स्वागत है",
    'goToHomeButtonText': "होम पर जाएं",
  },
  'pun': {
    'appTitle': 'ਸਾਡਾ ਵਾਹਨ',
    'searchHint': 'ਬੱਸ ਨੰਬਰ ਜਾਂ ਰੂਟ ਲਈ ਖੋਜੋ',
    'recentSearches': 'ਹਾਲੀਆ ਖੋਜਾਂ',
    'noRecentSearches': 'ਕੋਈ ਹਾਲੀਆ ਖੋਜ ਨਹੀਂ',
    'floatIconText': 'ਬੋਲਣ ਲਈ ਟੈਪ ਕਰੋ',
    'appBarTitle': 'ਸਾਡਾ ਵਾਹਨ',
    'drawerHeaderTitle': 'ਸਾਦੀਬਸ ',
    'recentSearchesTitle': 'ਹਾਲੀਆ ਖੋਜਾਂ',
    'noBusAvailable': 'ਤੁਹਾਡੇ ਚੁਣੇ ਹੋਏ ਰੂਟ \'ਤੇ ਕੋਈ ਬੱਸ ਉਪਲਬਧ ਨਹੀਂ ਹੈ',
    'arrivingIn': "ਪਹੁੰਚਣ ਵਿੱਚ ",
    'estimatedTime': "ਅਨੁਮਾਨਿਤ ਸਮਾਂ ",
    'sortBy': "ਤਰਤੀਬ ਬੱਧ ਕਰੋ",
    'arrivalTimeEarliest': "ਪਹੁੰਚਣ ਦਾ ਸਮਾਂ (ਸਭ ਤੋਂ ਪਹਿਲਾਂ)",
    'arrivalTimeLatest': "ਪਹੁੰਚਣ ਦਾ ਸਮਾਂ (ਸਭ ਤੋਂ ਬਾਅਦ)",
    'pickupDistanceNearest': "ਪਿਕਅੱਪ ਦੂਰੀ (ਸਭ ਤੋਂ ਨੇੜੇ)",
    'pickupDistanceFarthest': " ਪਿਕਅੱਪ ਦੂਰੀ (ਸਭ ਤੋਂ ਦੂਰ)",
    'dropDistanceNearest': "ਡ੍ਰੌਪ ਦੂਰੀ (ਸਭ ਤੋਂ ਨੇੜੇ)",
    'dropDistanceFarthest': "ਡ੍ਰੌਪ ਦੂਰੀ (ਸਭ ਤੋਂ ਦੂਰ)",
    'leavingHint': "ਕਿੱਥੋਂ ਜਾ ਰਹੇ ਹੋ",
    'goingHint': "ਕਿੱਥੇ ਜਾ ਰਹੇ ਹੋ",
    'departure': "ਰਵਾਨਗੀ",
    'searchButton': "ਬੱਸਾਂ ਲੱਭੋ",
    'signInButtonText': "ਖੋਜ ਇਤਿਹਾਸ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ",
    'listening': "ਸੁਣ ਰਹੇ ਹਾਂ...",
    'listeningHint': "ਆਪਣਾ ਪਿਕਅੱਪ ਅਤੇ ਮੰਜ਼ਿਲ ਦੱਸੋ",
    'tapToStop': "ਜਲਦੀ ਰੋਕਣ ਲਈ ਟੈਪ ਕਰੋ",
    'processing': "ਪ੍ਰਕਿਰਿਆ ਚੱਲ ਰਹੀ ਹੈ...",
    'understanding': "ਤੁਹਾਡੇ ਬੇਨਤੀ ਨੂੰ ਸਮਝਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
    'error': "ਇੱਕ ਗਲਤੀ ਹੋਈ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    'noSpeech': "ਕੋਈ ਬੋਲ ਨਹੀਂ ਸੁਣੀ ਗਈ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    'permissionDenied':
        "ਮਾਈਕ੍ਰੋਫੋਨ ਦੀ ਅਨੁਮਤੀ ਨਕਾਰ ਦਿੱਤੀ ਗਈ। ਕਿਰਪਾ ਕਰਕੇ ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਇਸਨੂੰ ਯੋਗ ਕਰੋ।",
    'recordingHint': "ਰਿਕਾਰਡਿੰਗ... ਰੋਕਣ ਲਈ ਟੈਪ ਕਰੋ",
    'retry': "ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    'confirm': "ਪੁਸ਼ਟੀ ਕਰੋ",
    'cancel': "ਰੱਦ ਕਰੋ",
    'microphonePermission': "ਮਾਈਕ੍ਰੋਫੋਨ ਅਨੁਮਤੀ",
    'recordAudio': "ਆਡੀਓ ਰਿਕਾਰਡ ਕਰੋ",
    'recording': "ਰਿਕਾਰਡਿੰਗ...",
    'processingRequest': "ਤੁਹਾਡੇ ਬੇਨਤੀ ਨੂੰ ਪ੍ਰਕਿਰਿਆ ਕਰ ਰਹੇ ਹਾਂ...",
    'goToHomeText': "ਹੋਮ 'ਤੇ ਜਾਓ",
    'recordingSuccess': "ਰਿਕਾਰਡਿੰਗ ਸਫਲ",
    'recordingFailed': "ਰਿਕਾਰਡਿੰਗ ਅਸਫਲ",
    'recordingComplete': "ਰਿਕਾਰਡਿੰਗ ਪੂਰੀ ਹੋ ਗਈ",
    'search': "ਖੋਜ",
    'leaveingHint': "ਕਿੱਥੋਂ ਜਾ ਰਹੇ ਹੋ",
    'signOut': "ਸਾਈਨ ਆਉਟ",
    'home': "ਹੋਮ",
    'language': "ਭਾਸ਼ਾ",
    'helpAndSupport': "ਮਦਦ ਅਤੇ ਸਹਾਇਤਾ",
    'feedback': "ਫੀਡਬੈਕ",
    'about': "ਬਾਰੇ",
    'welcome': "ਸਵਾਗਤ ਹੈ",
    'goToHomeButtonText': "ਹੋਮ 'ਤੇ ਜਾਓ"
  },
};
